; generated by Slic3r 1.3.0-dev on 2019-06-16 at 16:37:39

; external perimeters extrusion width = 0.50mm (4.97mm^3/s)
; perimeters extrusion width = 0.58mm (11.78mm^3/s)
; infill extrusion width = 0.58mm (15.71mm^3/s)
; solid infill extrusion width = 0.58mm (3.93mm^3/s)
; top infill extrusion width = 0.58mm (2.95mm^3/s)

M107
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle

;Automatically place parts
M361 P2
M361 P3
M361 P4
M361 P5
M361 P6
M361 P7
M361 P8
M361 P9
M361 P10
M361 P11
M361 P12
M361 P13
M361 P14
M361 P15
M361 P16
M361 P17
M361 P18
M361 P19
M361 P20
M361 P21

M107
; Filament-specific end gcode
;END gcode for filament

M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors

; filament used = 107.7mm (0.8cm3)
; filament used = 0.0mm (0.0cm3)
; total filament cost = 0.0

;<object name="VisionPNP_test.stl">

;<part id="2" name="Tiny2">
;  <position box="2"/>
;  <size height="1.87" width="5.38"/>
;  <shape>
;    <point x="-2.6" y="-2.6"/>
;    <point x="-2.6" y="2.6"/>
;    <point x="2.6" y="2.6"/>
;    <point x="2.6" y="-2.6"/>
;  </shape>
;  <pads>
;    <pad x1="-2.155" y1="-3.754" x2="-1.655" y2="-2.054"/>
;    <pad x1="-0.895" y1="-3.754" x2="-0.395" y2="-2.054"/>
;    <pad x1="0.375" y1="-3.754" x2="0.875" y2="-2.054"/>
;    <pad x1="1.645" y1="-3.754" x2="2.145" y2="-2.054"/>
;    <pad x1="-2.155" y1="2.054" x2="-1.655" y2="3.754"/>
;    <pad x1="-0.885" y1="2.054" x2="-0.385" y2="3.754"/>
;    <pad x1="0.385" y1="2.054" x2="0.885" y2="3.754"/>
;    <pad x1="1.655" y1="2.054" x2="2.155" y2="3.754"/>
;  </pads>
;  <destination x="20" y="10" z="0" orientation="45"/>
;</part>

;<part id="3" name="Tiny3">
;  <position box="3"/>
;  <size height="1.87" width="5.38"/>
;  <shape>
;    <point x="-2.6" y="-2.6"/>
;    <point x="-2.6" y="2.6"/>
;    <point x="2.6" y="2.6"/>
;    <point x="2.6" y="-2.6"/>
;  </shape>
;  <pads>
;    <pad x1="-2.155" y1="-3.754" x2="-1.655" y2="-2.054"/>
;    <pad x1="-0.895" y1="-3.754" x2="-0.395" y2="-2.054"/>
;    <pad x1="0.375" y1="-3.754" x2="0.875" y2="-2.054"/>
;    <pad x1="1.645" y1="-3.754" x2="2.145" y2="-2.054"/>
;    <pad x1="-2.155" y1="2.054" x2="-1.655" y2="3.754"/>
;    <pad x1="-0.885" y1="2.054" x2="-0.385" y2="3.754"/>
;    <pad x1="0.385" y1="2.054" x2="0.885" y2="3.754"/>
;    <pad x1="1.655" y1="2.054" x2="2.155" y2="3.754"/>
;  </pads>
;  <destination x="30" y="10" z="0" orientation="90"/>
;</part>

;<part id="4" name="Tiny4">
;  <position box="4"/>
;  <size height="1.87" width="5.38"/>
;  <shape>
;    <point x="-2.6" y="-2.6"/>
;    <point x="-2.6" y="2.6"/>
;    <point x="2.6" y="2.6"/>
;    <point x="2.6" y="-2.6"/>
;  </shape>
;  <pads>
;    <pad x1="-2.155" y1="-3.754" x2="-1.655" y2="-2.054"/>
;    <pad x1="-0.895" y1="-3.754" x2="-0.395" y2="-2.054"/>
;    <pad x1="0.375" y1="-3.754" x2="0.875" y2="-2.054"/>
;    <pad x1="1.645" y1="-3.754" x2="2.145" y2="-2.054"/>
;    <pad x1="-2.155" y1="2.054" x2="-1.655" y2="3.754"/>
;    <pad x1="-0.885" y1="2.054" x2="-0.385" y2="3.754"/>
;    <pad x1="0.385" y1="2.054" x2="0.885" y2="3.754"/>
;    <pad x1="1.655" y1="2.054" x2="2.155" y2="3.754"/>
;  </pads>
;  <destination x="40" y="10" z="0" orientation="135"/>
;</part>

;<part id="5" name="Tiny5">
;  <position box="5"/>
;  <size height="1.87" width="5.38"/>
;  <shape>
;    <point x="-2.6" y="-2.6"/>
;    <point x="-2.6" y="2.6"/>
;    <point x="2.6" y="2.6"/>
;    <point x="2.6" y="-2.6"/>
;  </shape>
;  <pads>
;    <pad x1="-2.155" y1="-3.754" x2="-1.655" y2="-2.054"/>
;    <pad x1="-0.895" y1="-3.754" x2="-0.395" y2="-2.054"/>
;    <pad x1="0.375" y1="-3.754" x2="0.875" y2="-2.054"/>
;    <pad x1="1.645" y1="-3.754" x2="2.145" y2="-2.054"/>
;    <pad x1="-2.155" y1="2.054" x2="-1.655" y2="3.754"/>
;    <pad x1="-0.885" y1="2.054" x2="-0.385" y2="3.754"/>
;    <pad x1="0.385" y1="2.054" x2="0.885" y2="3.754"/>
;    <pad x1="1.655" y1="2.054" x2="2.155" y2="3.754"/>
;  </pads>
;  <destination x="50" y="10" z="0" orientation="180"/>
;</part>

;<part id="6" name="Tiny6">
;  <position box="6"/>
;  <size height="1.87" width="5.38"/>
;  <shape>
;    <point x="-2.6" y="-2.6"/>
;    <point x="-2.6" y="2.6"/>
;    <point x="2.6" y="2.6"/>
;    <point x="2.6" y="-2.6"/>
;  </shape>
;  <pads>
;    <pad x1="-2.155" y1="-3.754" x2="-1.655" y2="-2.054"/>
;    <pad x1="-0.895" y1="-3.754" x2="-0.395" y2="-2.054"/>
;    <pad x1="0.375" y1="-3.754" x2="0.875" y2="-2.054"/>
;    <pad x1="1.645" y1="-3.754" x2="2.145" y2="-2.054"/>
;    <pad x1="-2.155" y1="2.054" x2="-1.655" y2="3.754"/>
;    <pad x1="-0.885" y1="2.054" x2="-0.385" y2="3.754"/>
;    <pad x1="0.385" y1="2.054" x2="0.885" y2="3.754"/>
;    <pad x1="1.655" y1="2.054" x2="2.155" y2="3.754"/>
;  </pads>
;  <destination x="60" y="10" z="0" orientation="225"/>
;</part>

;<part id="7" name="Tiny7">
;  <position box="7"/>
;  <size height="1.87" width="5.38"/>
;  <shape>
;    <point x="-2.6" y="-2.6"/>
;    <point x="-2.6" y="2.6"/>
;    <point x="2.6" y="2.6"/>
;    <point x="2.6" y="-2.6"/>
;  </shape>
;  <pads>
;    <pad x1="-2.155" y1="-3.754" x2="-1.655" y2="-2.054"/>
;    <pad x1="-0.895" y1="-3.754" x2="-0.395" y2="-2.054"/>
;    <pad x1="0.375" y1="-3.754" x2="0.875" y2="-2.054"/>
;    <pad x1="1.645" y1="-3.754" x2="2.145" y2="-2.054"/>
;    <pad x1="-2.155" y1="2.054" x2="-1.655" y2="3.754"/>
;    <pad x1="-0.885" y1="2.054" x2="-0.385" y2="3.754"/>
;    <pad x1="0.385" y1="2.054" x2="0.885" y2="3.754"/>
;    <pad x1="1.655" y1="2.054" x2="2.155" y2="3.754"/>
;  </pads>
;  <destination x="70" y="10" z="0" orientation="270"/>
;</part>

;<part id="8" name="R1">
;  <position box="8"/>
;  <size height="0.52" width="3.07"/>
;  <shape>
;    <point x="-1.535" y="-0.77"/>
;    <point x="-1.535" y="0.77"/>
;    <point x="1.535" y="0.77"/>
;    <point x="1.535" y="-0.77"/>
;  </shape>
;  <pads>
;    <pad x1="1.535" y1="-0.77" x2="1.535" y2="0.77"/>
;    <pad x1="-1.535" y1="-0.77" x2="-1.535" y2="0.77"/>
;  </pads>
;  <destination x="10" y="20" z="0" orientation="0"/>
;</part>

;<part id="9" name="R2">
;  <position box="9"/>
;  <size height="0.52" width="3.07"/>
;  <shape>
;    <point x="-1.535" y="-0.77"/>
;    <point x="-1.535" y="0.77"/>
;    <point x="1.535" y="0.77"/>
;    <point x="1.535" y="-0.77"/>
;  </shape>
;  <pads>
;    <pad x1="1.535" y1="-0.77" x2="1.535" y2="0.77"/>
;    <pad x1="-1.535" y1="-0.77" x2="-1.535" y2="0.77"/>
;  </pads>
;  <destination x="20" y="20" z="0" orientation="45"/>
;</part>

;<part id="10" name="R3">
;  <position box="10"/>
;  <size height="0.52" width="3.07"/>
;  <shape>
;    <point x="-1.535" y="-0.77"/>
;    <point x="-1.535" y="0.77"/>
;    <point x="1.535" y="0.77"/>
;    <point x="1.535" y="-0.77"/>
;  </shape>
;  <pads>
;    <pad x1="1.535" y1="-0.77" x2="1.535" y2="0.77"/>
;    <pad x1="-1.535" y1="-0.77" x2="-1.535" y2="0.77"/>
;  </pads>
;  <destination x="30" y="20" z="0" orientation="90"/>
;</part>

;<part id="11" name="R4">
;  <position box="11"/>
;  <size height="0.52" width="3.07"/>
;  <shape>
;    <point x="-1.535" y="-0.77"/>
;    <point x="-1.535" y="0.77"/>
;    <point x="1.535" y="0.77"/>
;    <point x="1.535" y="-0.77"/>
;  </shape>
;  <pads>
;    <pad x1="1.535" y1="-0.77" x2="1.535" y2="0.77"/>
;    <pad x1="-1.535" y1="-0.77" x2="-1.535" y2="0.77"/>
;  </pads>
;  <destination x="40" y="20" z="0" orientation="135"/>
;</part>

;<part id="12" name="R5">
;  <position box="12"/>
;  <size height="0.52" width="3.07"/>
;  <shape>
;    <point x="-1.535" y="-0.77"/>
;    <point x="-1.535" y="0.77"/>
;    <point x="1.535" y="0.77"/>
;    <point x="1.535" y="-0.77"/>
;  </shape>
;  <pads>
;    <pad x1="1.535" y1="-0.77" x2="1.535" y2="0.77"/>
;    <pad x1="-1.535" y1="-0.77" x2="-1.535" y2="0.77"/>
;  </pads>
;  <destination x="50" y="20" z="0" orientation="180"/>
;</part>

;<part id="13" name="R6">
;  <position box="13"/>
;  <size height="0.52" width="3.07"/>
;  <shape>
;    <point x="-1.535" y="-0.77"/>
;    <point x="-1.535" y="0.77"/>
;    <point x="1.535" y="0.77"/>
;    <point x="1.535" y="-0.77"/>
;  </shape>
;  <pads>
;    <pad x1="1.535" y1="-0.77" x2="1.535" y2="0.77"/>
;    <pad x1="-1.535" y1="-0.77" x2="-1.535" y2="0.77"/>
;  </pads>
;  <destination x="60" y="20" z="0" orientation="225"/>
;</part>

;<part id="14" name="R7">
;  <position box="14"/>
;  <size height="0.52" width="3.07"/>
;  <shape>
;    <point x="-1.535" y="-0.77"/>
;    <point x="-1.535" y="0.77"/>
;    <point x="1.535" y="0.77"/>
;    <point x="1.535" y="-0.77"/>
;  </shape>
;  <pads>
;    <pad x1="1.535" y1="-0.77" x2="1.535" y2="0.77"/>
;    <pad x1="-1.535" y1="-0.77" x2="-1.535" y2="0.77"/>
;  </pads>
;  <destination x="70" y="20" z="0" orientation="270"/>
;</part>

;<part id="15" name="LED1">
;  <position box="15"/>
;  <size height="1.05" width="3.17"/>
;  <shape>
;    <point x="-1.585" y="-0.8"/>
;    <point x="0.015" y="-0.8"/>
;    <point x="0.015" y="-0.27"/>
;    <point x="-1.185" y="-0.27"/>
;    <point x="-1.185" y="0.26"/>
;    <point x="0.015" y="0.26"/>
;    <point x="0.015" y="0.8"/>
;    <point x="-1.585" y="0.8"/>
;  </shape>
;  <pads>
;    <pad x1="0.785" y1="-0.8" x2="1.585" y2="0.8"/>
;    <pad x1="-1.585" y1="-0.8" x2="-1.185" y2="0.8"/>
;  </pads>
;  <destination x="10" y="30" z="0" orientation="0"/>
;</part>

;<part id="16" name="LED2">
;  <position box="16"/>
;  <size height="1.05" width="3.17"/>
;  <shape>
;    <point x="-1.585" y="-0.8"/>
;    <point x="0.015" y="-0.8"/>
;    <point x="0.015" y="-0.27"/>
;    <point x="-1.185" y="-0.27"/>
;    <point x="-1.185" y="0.26"/>
;    <point x="0.015" y="0.26"/>
;    <point x="0.015" y="0.8"/>
;    <point x="-1.585" y="0.8"/>
;  </shape>
;  <pads>
;    <pad x1="0.785" y1="-0.8" x2="1.585" y2="0.8"/>
;    <pad x1="-1.585" y1="-0.8" x2="-1.185" y2="0.8"/>
;  </pads>
;  <destination x="20" y="30" z="0" orientation="45"/>
;</part>

;<part id="17" name="LED3">
;  <position box="17"/>
;  <size height="1.05" width="3.17"/>
;  <shape>
;    <point x="-1.585" y="-0.8"/>
;    <point x="0.015" y="-0.8"/>
;    <point x="0.015" y="-0.27"/>
;    <point x="-1.185" y="-0.27"/>
;    <point x="-1.185" y="0.26"/>
;    <point x="0.015" y="0.26"/>
;    <point x="0.015" y="0.8"/>
;    <point x="-1.585" y="0.8"/>
;  </shape>
;  <pads>
;    <pad x1="0.785" y1="-0.8" x2="1.585" y2="0.8"/>
;    <pad x1="-1.585" y1="-0.8" x2="-1.185" y2="0.8"/>
;  </pads>
;  <destination x="30" y="30" z="0" orientation="90"/>
;</part>

;<part id="18" name="LED4">
;  <position box="18"/>
;  <size height="1.05" width="3.17"/>
;  <shape>
;    <point x="-1.585" y="-0.8"/>
;    <point x="0.015" y="-0.8"/>
;    <point x="0.015" y="-0.27"/>
;    <point x="-1.185" y="-0.27"/>
;    <point x="-1.185" y="0.26"/>
;    <point x="0.015" y="0.26"/>
;    <point x="0.015" y="0.8"/>
;    <point x="-1.585" y="0.8"/>
;  </shape>
;  <pads>
;    <pad x1="0.785" y1="-0.8" x2="1.585" y2="0.8"/>
;    <pad x1="-1.585" y1="-0.8" x2="-1.185" y2="0.8"/>
;  </pads>
;  <destination x="40" y="30" z="0" orientation="135"/>
;</part>

;<part id="19" name="LED5">
;  <position box="19"/>
;  <size height="1.05" width="3.17"/>
;  <shape>
;    <point x="-1.585" y="-0.8"/>
;    <point x="0.015" y="-0.8"/>
;    <point x="0.015" y="-0.27"/>
;    <point x="-1.185" y="-0.27"/>
;    <point x="-1.185" y="0.26"/>
;    <point x="0.015" y="0.26"/>
;    <point x="0.015" y="0.8"/>
;    <point x="-1.585" y="0.8"/>
;  </shape>
;  <pads>
;    <pad x1="0.785" y1="-0.8" x2="1.585" y2="0.8"/>
;    <pad x1="-1.585" y1="-0.8" x2="-1.185" y2="0.8"/>
;  </pads>
;  <destination x="50" y="30" z="0" orientation="180"/>
;</part>

;<part id="20" name="LED6">
;  <position box="20"/>
;  <size height="1.05" width="3.17"/>
;  <shape>
;    <point x="-1.585" y="-0.8"/>
;    <point x="0.015" y="-0.8"/>
;    <point x="0.015" y="-0.27"/>
;    <point x="-1.185" y="-0.27"/>
;    <point x="-1.185" y="0.26"/>
;    <point x="0.015" y="0.26"/>
;    <point x="0.015" y="0.8"/>
;    <point x="-1.585" y="0.8"/>
;  </shape>
;  <pads>
;    <pad x1="0.785" y1="-0.8" x2="1.585" y2="0.8"/>
;    <pad x1="-1.585" y1="-0.8" x2="-1.185" y2="0.8"/>
;  </pads>
;  <destination x="60" y="30" z="0" orientation="225"/>
;</part>

;<part id="21" name="LED7">
;  <position box="21"/>
;  <size height="1.05" width="3.17"/>
;  <shape>
;    <point x="-1.585" y="-0.8"/>
;    <point x="0.015" y="-0.8"/>
;    <point x="0.015" y="-0.27"/>
;    <point x="-1.185" y="-0.27"/>
;    <point x="-1.185" y="0.26"/>
;    <point x="0.015" y="0.26"/>
;    <point x="0.015" y="0.8"/>
;    <point x="-1.585" y="0.8"/>
;  </shape>
;  <pads>
;    <pad x1="0.785" y1="-0.8" x2="1.585" y2="0.8"/>
;    <pad x1="-1.585" y1="-0.8" x2="-1.185" y2="0.8"/>
;  </pads>
;  <destination x="70" y="30" z="0" orientation="270"/>
;</part>

;</object>


; avoid_crossing_perimeters = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; before_layer_gcode =
; between_objects_gcode =
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_connections_width = 0
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_cost = 0
; filament_density = 0
; filament_diameter = 3
; filament_max_volumetric_speed = 0
; filament_notes = ""
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_speed = 30
; first_layer_temperature = 205
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; has_heatbed = 1
; infill_acceleration = 0
; infill_first = 0
; interior_brim_width = 0
; layer_gcode =
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.15
; min_print_speed = 10
; min_skirt_length = 0
; notes =
; nozzle_diameter = 0.5
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process =
; pressure_advance = 0
; printer_notes =
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; temperature = 200
; threads = 4
; toolchange_gcode =
; travel_speed = 130
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; z_steps_per_mm = 0
; adaptive_slicing = 0
; adaptive_slicing_quality = 75%
; conductive_cavity_offset = 0.5
; conductive_pnp_manual_gcode = G91\nG1 Z10 F2000\nG90\nM0\n
; conductive_wire_channel_width = 0.8
; conductive_wire_extrusion_overlap = 1
; conductive_wire_extrusion_width = 0.5
; conductive_wire_first_extrusion_overlap = 1.5
; conductive_wire_overlap_min_extrusion_length = 0
; conductive_wire_slope_overlap = 1.5
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.5
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.4
; match_horizontal_surfaces = 0
; raft_layers = 0
; regions_overlap = 0
; seam_position = aligned
; sequential_print_priority = 0
; support_material = 0
; support_material_angle = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_extrusion_width = 0
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_threshold = 60%
; xy_size_compensation = 0
; bottom_infill_pattern = rectilinear
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 60
; conductive_wire_extruder = 2
; conductive_wire_speed = 2
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 20%
; fill_gaps = 1
; fill_pattern = stars
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 55%
; infill_speed = 80
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 60
; perimeters = 3
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_infill_pattern = rectilinear
; top_solid_infill_speed = 15
; top_solid_layers = 3